name: IPTV Otomatik Guncelle
on:
  schedule:
    - cron: '0 3 * * *' # Her gece Türkiye saatiyle 06:00 (UTC 03:00) gibi çalışır
  workflow_dispatch: # Elinle "Run" butonu ekler (Test etmek için)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Kütüphaneleri Yukle
        run: |
          pip install undetected-chromedriver selenium

      - name: Botu Calistir
        run: python iptv_bot.py

      - name: Degisiklikleri Kaydet
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add iptv_listem.m3u
          git commit -m "Oto Guncelleme yapıldı" || exit 0
          git push
